name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: navigate to directory
        run: cd lambda/custom && npm install
      - name: lint
        run: cd lambda/custom && npm run lint
#      - uses: stefanoeb/eslint-action@1.0.2
